spring:
  datasource:
    url: jdbc:mysql://localhost:3306/btaplon_tmdt
    username: root
    password: Gianglq2004@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
#
#jwt:
#  secret: "replace-with-256-bit-secret-at-least-32-chars-xxxxxxxxxxxxxxxxxxxx"
#  expiration-minutes: 120
#
#springdoc:
#  api-docs.enabled: true
#  swagger-ui.path: /swagger-ui


file:
  upload-dir: uploads


#vnpay:
#  tmnCode: I8G3WS7K
#  hashSecret: TCZ7GEB5SDYQ7SAYU9VUXMIU6RQAFAL1
#  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
#  returnUrl: http://localhost:8080/api/payments/vnpay-return
#  ipnUrl: http://localhost:8080/api/payments/vnpay-ipn
#  currCode: VND
#  locale: vn

pay:
  vnpay:
    tmnCode: I8G3WS7K
    secretKey: TCZ7GEB5SDYQ7SAYU9VUXMIU6RQAFAL1
    payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    returnUrl: http://localhost:4200/payment/success
    ipnUrl: http://localhost:8080/api/payments/vnpay-ipn
    version: 2.1.0
    currCode: VND
    locale: vn
    orderType: other
    expireMinutes: 15
